simulator:
  run_id: k8s_import_grafana_1752595626
  run_description: Imported Kubernetes configuration k8s_import_grafana_1752595626
  associated_scenario: k8s_import_grafana_1752595626
  timestep: 60
  start_step: 1
  limit: 60
  instance_pool_size: 1000
  logging: 1
  clusters:
  - KubernetesCluster:
      type: KubernetesCluster
      name: default
      node_count: 3
      node_type: m5.large
      autoscaling: true
  deployments_directory: deployments
  deployments:
  - graphite
  - graphite-write-proxy
  - graphite-querier
  - cortex-gw
  - graphite-config-controller
  - pyroscope-querier
  - canary-exporter
  - pyroscope-distributor
  - pyroscope-ad-hoc-profiles
  - pyroscope-query-scheduler
  - pyroscope-bucket-info-exporter
  - pyroscope-admin
  - pyroscope-tenant-settings
  - cortex-gw
  - pyroscope-query-frontend
  - cost-attribution-operator
  - loki-quotas-service-metrics
  - quotas-service-api
  - bloom-builder
  - loki-autoscaler-metrics
  - cortex-gw-internal
  - cloud-logs-archiver
  - querier-burst
  - spec-exporter
  - querier
  - adaptive-logs-api
  - quotas-service-operator
  - cell-bucket-exporter
  - loki-freetier-limiter-metrics
  - query-scheduler
  - archiver-operator
  - loki-internal-release
  - parallel-querier-burst-backup
  - distributor
  - parallel-query-scheduler
  - cortex-gw
  - metrics-instance-mapper
  - loki-canary
  - parallel-querier-burst
  - ruler
  - rollout-operator
  - parallel-querier
  - querier-burst-backup
  - pv-deleter
  - overrides-exporter
  - query-frontend
  - parallel-query-frontend
  - influx-proxy-writes
  - cortex-gw
  - graphite
  - graphite-write-proxy
  - graphite-querier
  - cortex-gw
  - graphite-config-controller
  - smtprelay
  - mysql-exporter-prod-us-east-0-hosted-grafana-shared-5-mysql8
  - rds-proxy-prod-us-east-0-hosted-grafana-shared-3-mysql8
  - packing-peanuts-large
  - rds-proxy-prod-us-east-0-hosted-grafana-shared-6-mysql8
  - hosted-grafana-api
  - rds-proxy-prod-us-east-0-hosted-grafana-shared-12
  - pdc-agent-stack-781953
  - shared-12-exporter
  - shared-9-exporter
  - mysql-exporter-prod-us-east-0-hosted-grafana-shared-3-mysql8
  - rds-proxy-prod-us-east-0-hosted-grafana-shared-5-mysql8
  - carbon-relay-ng
  - mysql-exporter-prod-us-east-0-hosted-grafana-shared-6-mysql8
  - shared-11-exporter
  - redis-cluster-proxy
  - hosted-grafana-controller
  - mysql-exporter-prod-us-east-0-hosted-grafana-shared-8-mysql8
  - hosted-grafana-gateway
  - rds-proxy-prod-us-east-0-hosted-grafana-shared-9
  - shared-10-exporter
  - mysql-exporter-prod-us-east-0-hosted-grafana-shared-1-mysql8
  - rds-proxy-prod-us-east-0-hosted-grafana-shared-7-mysql8
  - rds-proxy-prod-us-east-0-hosted-grafana-shared-2-mysql8
  - mysql-exporter-prod-us-east-0-hosted-grafana-shared-4-mysql8
  - pdc-auth-gw
  - pdc-agent-stack-675576
  - rds-proxy-prod-us-east-0-hosted-grafana-shared-11
  - rds-proxy-prod-us-east-0-hosted-grafana-shared-8-mysql8
  - private-datasource-connect
  - mysql-exporter-prod-us-east-0-hosted-grafana-shared-7-mysql8
  - rds-proxy-prod-us-east-0-hosted-grafana-shared-1-mysql8
  - rds-proxy-prod-us-east-0-hosted-grafana-shared-4-mysql8
  - mysql-exporter-prod-us-east-0-hosted-grafana-shared-2-mysql8
  - api-mysql8-exporter
  - go-feature-flag
  - rds-proxy-prod-us-east-0-hosted-grafana-shared-10
  - ruler-querier
  - ruler-query-frontend
  - limitskafka-exporter
  - aggregation-recommendations
  - aggregations-api
  - cortex-gw-internal
  - querier-burst
  - aggregator-partitioner-metrics
  - querier
  - memberlist-seed
  - aggregator-warpstream-partitioner-metrics
  - query-scheduler
  - distributor
  - freetier-limit-merge
  - adaptive-metrics-canary
  - cortex-gw
  - ruler
  - mimir-aggregation-dpm-overrider
  - rollout-operator
  - querier-burst-backup
  - limits-operator-redpanda-console
  - kafka-exporter
  - mimir-internal-release
  - config-api
  - overrides-exporter
  - ruler-query-scheduler
  - mimir-config-exporter
  - continuous-test
  - query-frontend
  - mimir-bucket-info-exporter
  - ruler-querier
  - ruler-query-frontend
  - limitskafka-exporter
  - aggregation-recommendations
  - aggregations-api
  - cortex-gw-internal
  - querier-burst
  - aggregator-partitioner-metrics
  - querier
  - memberlist-seed
  - aggregator-warpstream-partitioner-metrics
  - query-scheduler
  - distributor
  - freetier-limit-merge
  - adaptive-metrics-canary
  - cortex-gw
  - ruler
  - mimir-aggregation-dpm-overrider
  - rollout-operator
  - querier-burst-backup
  - limits-operator-redpanda-console
  - kafka-exporter
  - mimir-internal-release
  - config-api
  - overrides-exporter
  - ruler-query-scheduler
  - mimir-config-exporter
  - continuous-test
  - query-frontend
  - mimir-bucket-info-exporter
  - metrics-generator
  - cortex-gw-internal
  - compactor
  - vulture
  - querier
  - tempo-bucket-info-exporter
  - distributor
  - tempo-autoscaler-metrics
  - cortex-gw
  - metrics-instance-mapper
  - query-frontend
  - ruler-querier
  - ruler-query-frontend
  - limitskafka-exporter
  - aggregation-recommendations
  - aggregations-api
  - cortex-gw-internal
  - querier-burst
  - aggregator-partitioner-metrics
  - querier
  - memberlist-seed
  - aggregator-warpstream-partitioner-metrics
  - query-scheduler
  - mimir-target-series-exporter
  - distributor
  - freetier-limit-merge
  - adaptive-metrics-canary
  - cortex-gw
  - ruler
  - mimir-aggregation-dpm-overrider
  - rollout-operator
  - querier-burst-backup
  - limits-operator-redpanda-console
  - kafka-exporter
  - mimir-internal-release
  - config-api
  - overrides-exporter
  - ruler-query-scheduler
  - mimir-config-exporter
  - continuous-test
  - query-frontend
  - mimir-bucket-info-exporter
  - metrics-generator
  - cortex-gw-internal
  - compactor
  - vulture
  - querier
  - tempo-bucket-info-exporter
  - distributor
  - tempo-autoscaler-metrics
  - cortex-gw
  - metrics-instance-mapper
  - query-frontend
  - loki-quotas-service-metrics
  - quotas-service-api
  - bloom-builder
  - loki-autoscaler-metrics
  - cortex-gw-internal
  - cloud-logs-archiver
  - querier-burst
  - spec-exporter
  - querier
  - adaptive-logs-api
  - quotas-service-operator
  - cell-bucket-exporter
  - loki-freetier-limiter-metrics
  - query-scheduler
  - archiver-operator
  - loki-internal-release
  - parallel-querier-burst-backup
  - distributor
  - parallel-query-scheduler
  - cortex-gw
  - metrics-instance-mapper
  - loki-canary
  - parallel-querier-burst
  - ruler
  - rollout-operator
  - parallel-querier
  - querier-burst-backup
  - pv-deleter
  - overrides-exporter
  - query-frontend
  - parallel-query-frontend
  - aws-load-balancer-controller
  - coredns
  - ebs-csi-controller
  - metrics-server
  - influx-proxy-writes
  - cortex-gw
  - memcached-aggregation-cache
  - memcached-metric-name-cache
  - memcached-cc-deduplicator-cache
  - memcached-deduplicator-cache
  - pyroscope-compactor
  - freetier-limiter
  - pyroscope-ingester
  - pyroscope-store-gateway
  - memcached-l2
  - pattern-ingester
  - template-miner
  - compactor
  - memcached-index-queries
  - bloom-gateway
  - ingester-zone-a
  - bloom-planner
  - freetier-limiter
  - memcached-extstore
  - ingester-zone-c
  - ingester-zone-b
  - ruler
  - memcached-frontend
  - index-gateway
  - memcached
  - memcached-aggregation-cache
  - memcached-metric-name-cache
  - memcached-cc-deduplicator-cache
  - memcached-deduplicator-cache
  - redis-alerting-3
  - redis-live-6
  - redis-alerting-2
  - redis-alerting-5
  - redis-alerting-4
  - redis-live-3
  - redis-live
  - redis-alerting
  - redis-cluster
  - redis-live-2
  - redis-live-5
  - redis-live-4
  - kafka-zone-a
  - limits-operator
  - aggregator-zone-a
  - aggregator-cardinality-summary-querier
  - compactor
  - memcached-index-queries
  - ingester-zone-a
  - kafkactr
  - store-gateway-zone-a
  - store-gateway-zone-b
  - limitskafka
  - ingester-zone-c
  - ingester-zone-b
  - store-gateway-zone-c
  - memcached-frontend
  - memcached-metadata
  - kafka-zone-b
  - memcached
  - kafka-zone-a
  - limits-operator
  - aggregator-zone-a
  - aggregator-cardinality-summary-querier
  - compactor
  - memcached-index-queries
  - ingester-zone-a
  - kafkactr
  - store-gateway-zone-a
  - store-gateway-zone-b
  - limitskafka
  - ingester-zone-c
  - ingester-zone-b
  - store-gateway-zone-c
  - memcached-frontend
  - memcached-metadata
  - kafka-zone-b
  - memcached
  - metrics-generator
  - ingester
  - memcached-parquet-page-01
  - memcached-01
  - memcached-frontend-search-01
  - kafka-zone-a
  - limits-operator
  - aggregator-zone-a
  - aggregator-cardinality-summary-querier
  - compactor
  - memcached-index-queries
  - ingester-zone-a
  - kafkactr
  - store-gateway-zone-a
  - store-gateway-zone-b
  - limitskafka
  - ingester-zone-c
  - ingester-zone-b
  - store-gateway-zone-c
  - memcached-frontend
  - memcached-metadata
  - kafka-zone-b
  - memcached
  - metrics-generator
  - ingester
  - memcached-parquet-page-01
  - memcached-01
  - memcached-frontend-search-01
  - memcached-l2
  - pattern-ingester
  - template-miner
  - compactor
  - memcached-index-queries
  - bloom-gateway
  - ingester-zone-a
  - bloom-planner
  - freetier-limiter
  - memcached-extstore
  - ingester-zone-c
  - ingester-zone-b
  - ruler
  - memcached-frontend
  - index-gateway
  - memcached
  - critical-prometheus
  - node-local-dns
  - aws-node
  - ebs-csi-node
