apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-warpstream-partitioner-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator-warpstream-partitioner-metrics
  template:
    metadata:
      labels:
        app: aggregator-warpstream-partitioner-metrics
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: aggregator-warpstream-partitioner-metrics-container
        image: nginx:latest
        resources:
          requests:
            cpu: '0.1'
            memory: 128Mi
