apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloom-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bloom-gateway
  template:
    metadata:
      labels:
        app: bloom-gateway
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: bloom-gateway-container
        image: nginx:latest
        resources:
          requests:
            cpu: '1.5'
            memory: 2048Mi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                name: memcached-extstore
            topologyKey: kubernetes.io/hostname
      tolerations:
      - effect: NoSchedule
        key: type
        operator: Equal
        value: local-ssd
