apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: limits-operator-redpanda-console-pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: limits-operator-redpanda-console
