apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir-internal-release
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir-internal-release
  template:
    metadata:
      labels:
        app: mimir-internal-release
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: mimir-internal-release-container
        image: nginx:latest
        resources:
          requests:
            cpu: '0.1'
            memory: 128Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: arm64
      - effect: NoSchedule
        key: arch
        operator: Equal
        value: arm64
