apiVersion: apps/v1
kind: Deployment
metadata:
  name: parallel-querier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parallel-querier
  template:
    metadata:
      labels:
        app: parallel-querier
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: parallel-querier-container
        image: nginx:latest
        resources:
          requests:
            cpu: '2.0'
            memory: 2048Mi
