apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyroscope-query-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pyroscope-query-frontend
  template:
    metadata:
      labels:
        app: pyroscope-query-frontend
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: pyroscope-query-frontend-container
        image: nginx:latest
        resources:
          requests:
            cpu: '0.1'
            memory: 256Mi
