apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rds-proxy-prod-us-east-0-hosted-grafana-shared-7-mysql8-pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: rds-proxy-prod-us-east-0-hosted-grafana-shared-7-mysql8
