apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruler-query-scheduler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ruler-query-scheduler
  template:
    metadata:
      labels:
        app: ruler-query-scheduler
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: ruler-query-scheduler-container
        image: nginx:latest
        resources:
          requests:
            cpu: '2.0'
            memory: 1024Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                name: ruler-query-scheduler
            topologyKey: kubernetes.io/hostname
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: arm64
      - effect: NoSchedule
        key: arch
        operator: Equal
        value: arm64
