apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulture
  template:
    metadata:
      labels:
        app: vulture
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: vulture-container
        image: nginx:latest
        resources:
          requests:
            cpu: '0.1'
            memory: 128Mi
