apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["m-4x-amd64-linux", "m-8x-amd64-linux"]
      nodeClassRef:
        name: default
        kind: KWOKNodeClass
        group: karpenter.kwok.sh
  limits:
    cpu: "1000"
  disruption:
    consolidateWhen: WhenCostJustifiesDisruption
    decisionRatioThreshold: 0.50
    consolidateAfter: 30s
